#!/bin/bash

NORMAL='\033[0m'

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'

# Font style
BOLD='\033[1m'

# Logging
log_error() {
   echo -e "${NORMAL}[${RED}ERROR${NORMAL}] $@" 1>&2
}

log_success() {
   echo -e "${NORMAL}[${GREEN}SUCCESS${NORMAL}] $@"
}

log_warning() {
   echo -e "${NORMAL}[${YELLOW}WARNING${NORMAL}] $@"
}

log_info() {
   echo -e "${NORMAL}[${BLUE}INFO${NORMAL}] $@"
}

# Helpers
bold() {
  echo -e "${BOLD}$1${NORMAL}"
}